# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: video-agents-foundry-solution
metadata:
  template: video-agents-foundry-solution@1.0.0
requiredVersions:
  azd: ">=1.14.0"
workflows:
  up:
    steps:
      - azd: provision
infra:
  provider: bicep
  path: infra
  module: main
hooks:
  preup:
    windows:
      shell: sh
      run: ./hooks/validate-env.sh
      interactive: true
      continueOnError: false
    posix:
      shell: sh
      run: ./hooks/validate-env.sh
      interactive: true
      continueOnError: false
  preprovision:
    windows:
      shell: sh
      run: ./hooks/preprovision.sh
      interactive: true
    posix:
      shell: sh
      run: ./hooks/preprovision.sh
      interactive: true
  postprovision:
    windows:
      shell: sh
      run: ./hooks/postprovision.sh
    posix:
      shell: sh
      run: ./hooks/postprovision.sh
  postup:
    windows:
      shell: sh
      run: ./hooks/postup.ps1
      interactive: true
    posix:
      shell: sh
      run: ./hooks/postup.sh
      interactive: true
pipeline:
  variables:
    - AZURE_RESOURCE_GROUP
    - AZURE_PRINCIPAL_ID
    - CREATE_ROLE_FOR_USER
    - KUBERNETES_VERSION
    - SYSTEM_VM_SIZE
    - WORKLOAD_VM_SIZE
    - DEEPSTREAM_GPU_VM_SIZE
    - INFERENCE_GPU_VM_SIZE
    - DEEPSTREAM_GPU_MAX_NODE_COUNT
    - CREATE_FOUNDRY_PROJECT
    - AI_MODEL_NAME
    - AI_MODEL_VERSION
    - AI_MODEL_CAPACITY
    - MEDIA_STREAMER_ENABLED
    - STORAGE_SKU_NAME
